// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WatchStoreApi.Data;

#nullable disable

namespace WatchStoreApi.Migrations
{
    [DbContext(typeof(WatchStoreDbContext))]
    [Migration("20241028165336_RolexAdd")]
    partial class RolexAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WatchStoreApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Oyster, 36 mm, Oystersteel and white gold",
                            Image = "/Images/Rolex/datejust36.png",
                            Name = "Rolex Datejust 36",
                            Price = 18500m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Oyster, 41 mm, Oystersteel",
                            Image = "/Images/Rolex/submariner41.png",
                            Name = "Rolex Submariner 41",
                            Price = 18300m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Oyster, 40 mm, Oystersteel",
                            Image = "/Images/Rolex/gmt-master2.png",
                            Name = "Rolex GMT-MASTER II",
                            Price = 21650m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Oyster, 40 mm, Everose gold",
                            Image = "/Images/Rolex/daydate40.png",
                            Name = "Rolex Day-Date 40",
                            Price = 87300m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Oyster, 40 mm, white gold",
                            Image = "/Images/Rolex/daytonaCosmo.png",
                            Name = "Rolex Cosmograph Daytona",
                            Price = 89500m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Oyster, 41 mm, Oystersteel",
                            Image = "/Images/Rolex/perpetual41.png",
                            Name = "Rolex Oyster Perpetual 41",
                            Price = 12850m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Oyster, 42 mm, RLX titanium",
                            Image = "/Images/Rolex/yachmaster42.png",
                            Name = "Rolex YachtMaster 42",
                            Price = 28450m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Oyster, 43 mm, Oystersteel and yellow gold",
                            Image = "/Images/Rolex/seadweller43.png",
                            Name = "Rolex Sea-Dweller",
                            Price = 38000m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Oyster, 44 mm, yellow gold",
                            Image = "/Images/Rolex/deepsea44.png",
                            Name = "Rolex Deepsea",
                            Price = 109600m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Oyster, 40 mm, Oystersteel",
                            Image = "/Images/Rolex/airking40.png",
                            Name = "Rolex Air-King",
                            Price = 14950m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Oyster, 36 mm, Oystersteel and yellow gold",
                            Image = "/Images/Rolex/explorer36.png",
                            Name = "Rolex Explorer 36",
                            Price = 24800m,
                            Quantity = 18
                        });
                });

            modelBuilder.Entity("WatchStoreApi.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rolex"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hublot"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Patek Philippe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Breitling"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tissot"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Omega"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
